/* eslint-disable no-shadow */
export enum Packages {
	GraphqlCodegenCli = '@graphql-codegen/cli',
	GraphqlCodegenTypescript = '@graphql-codegen/typescript',
	GraphqlCodegenTypescriptResolvers = '@graphql-codegen/typescript-resolvers',
	ApolloClient = '@apollo/client',
	ApolloServer = '@apollo/server',
	Bcryptjs = 'bcryptjs',
	Bcryptts = 'bcrypt-ts',
	Cors = 'cors',
	Dotenv = 'dotenv',
	Express = 'express',
	Graphql = 'graphql',
	GraphqlTag = 'graphql-tag',
	Jsonwebtoken = 'jsonwebtoken',
	Mongoose = 'mongoose',
	Nodemon = 'nodemon',
	Pg = 'pg',
	Tsup = 'tsup',
	Tsx = 'tsx',
	TypesBcryptjs = '@types/bcryptjs',
	TypesCors = '@types/cors',
	TypesExpress = '@types/express',
	TypesJsonwebtoken = '@types/jsonwebtoken',
	TypesNode = '@types/node',
	TypesNodemon = '@types/nodemon',
	TypesPg = '@types/pg',
	Typescript = 'typescript',
}
