// eslint-disable-next-line no-shadow
export enum Packages {
	JWT = 'jsonwebtoken',
	CORS = 'cors',
	BCRYPTJS = 'bcryptjs',
	TSX = 'tsx',
	DOTENV = 'dotenv',
	GRAPHQL_CODEGEN_CLI = '@graphql-codegen/cli',
	GRAPHQL_CODEGEN_TYPESCRIPT = '@graphql-codegen/typescript',
	GRAPHQL_CODEGEN_TYPESCRIPT_RESOLVERS = '@graphql-codegen/typescript-resolvers',
	NODEMON = 'nodemon',
	TSUP = 'tsup',
	APOLLO_CLIENT = '@apollo/client',
	GRAPHQL = 'graphql',
	TYPESCRIPT = 'typescript',
	TYPES_NODE = '@types/node',
	MONGOOSE = 'mongoose',
	PG = 'pg',
	APOLLO_SERVER = '@apollo/server',
	GRAPHQL_TAG = 'graphql-tag',
	JWT_TYPE = '@types/jsonwebtoken',
	BCRYPT_TYPE = '@types/bcryptjs',
	CORS_TYPE = '@types/cors',
	NODEMON_TYPE = '@types/nodemon',
	PG_TYPE = '@types/pg',
}
